# Settings file keys
MODDED_CONTENT_FOLDER_PATHS = 'MODDED_CONTENT_FOLDER_PATHS'
LATEST_CONTENT_FOLDER_PATH = 'LATEST_CONTENT_FOLDER_PATH'
PREVIOUS_CONTENT_FOLDER_PATH = 'PREVIOUS_CONTENT_FOLDER_PATH'
VERBOSE_OUTPUT = 'VERBOSE_OUTPUT'

PATH = 'PATH'
LATEST = 'LATEST_VERSION'
PREVIOUS = 'PREVIOUS_VERSION'

MOD_FILE_EXTENSIONS = ['.uexp', '.uasset']