SECTION_GENERAL = 'GENERAL'
SECTION_MOD_VALIDATOR = 'MOD_VALIDATOR'
SECTION_UPDATE_ALTERATIONS_MONITOR = 'UPDATE_ALTERATIONS_MONITOR'

MODDED_CONTENT_FOLDER_PATHS = 'MODDED_CONTENT_FOLDER_PATHS'
LATEST_CONTENT_FOLDER_PATH = 'LATEST_CONTENT_FOLDER_PATH'
PREVIOUS_CONTENT_FOLDER_PATH = 'PREVIOUS_CONTENT_FOLDER_PATH'

LATEST = 'LATEST'
PREVIOUS = 'PREVIOUS'
