MODDED_CONTENT_FOLDER_PATHS = 'MODDED_CONTENT_FOLDER_PATHS'
LATEST_CONTENT_FOLDER_PATH = 'LATEST_CONTENT_FOLDER_PATH'
PREVIOUS_CONTENT_FOLDER_PATH = 'PREVIOUS_CONTENT_FOLDER_PATH'

PATH = 'PATH'
LATEST = 'LATEST_VERSION'
PREVIOUS = 'PREVIOUS_VERSION'
